image: node:16

stages:
  - build

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

before_script:
  - echo "Running on Shell Executor"
  - export PATH=$PATH:$(npm bin)
  - node -v
  - npm -v

build:
  stage: build
  tags:
    - shell
  script:
    - npm install
    - npm run build
  cache:
    key: none
  artifacts:
    paths:
      - dist/
